source 'http://rubygems.org'
gem 'therubyracer'

gem 'middleman',               '~> 3.3.12'
gem 'middleman-autoprefixer',  '~>  2.5.0'
gem 'middleman-blog'
gem 'middleman-deploy',        '~> 1.0.0'
gem 'middleman-favicon-maker', '~>  3.7'
gem 'middleman-google-analytics'
gem 'middleman-livereload',    '~>  3.4.2'
gem 'middleman-minify-html',   '~>  3.4.1'
gem 'middleman-navtree'
gem 'middleman-sitemap',       '~> 0.0.13'
gem 'middleman-sitemap-ping'
gem 'middleman-syntax'

gem 'nokogiri','~> 1.6.3.1'
gem 'slim',    '~> 3.0.2'
gem 'builder', '~> 3.2.2'
gem 'better_errors'
gem 'oga'
